#
# (C) Copyright 2016-2017 HP Development Company, L.P.
# Confidential computer software. Valid license from HP required for possession, use or copying.
# Consistent with FAR 12.211 and 12.212, Commercial Computer Software,
# Computer Software Documentation, and Technical Data for Commercial Items are licensed
# to the U.S. Government under vendor's standard commercial license.
#

version: "2"
services:
  elsd:
    image: hpccp/elsd:latest
    container_name: elsd
    build:
      context: .
      args:
        - NO_PROXY
        - HTTP_PROXY
        - HTTPS_PROXY
        - no_proxy
        - http_proxy
        - https_proxy
    environment:
      - ELS_ADDRESS=localhost
      - ELS_PORT=8082
    ports:
      - "8082:8082" # gRPC
    links:
      - dynamodb
  dynamodb:
      image: peopleperhour/dynamodb
      ports:
        - "8000:8000" # HTTP
