// Code generated by protoc-gen-go.
// source: els.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	els.proto

It has these top-level messages:
	RoutingKeyRequest
	ServiceInstanceResponse
	AddRoutingKeyRequest
	DeleteRoutingKeyRequest
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RoutingKeyRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *RoutingKeyRequest) Reset()                    { *m = RoutingKeyRequest{} }
func (m *RoutingKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*RoutingKeyRequest) ProtoMessage()               {}
func (*RoutingKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RoutingKeyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceInstanceResponse struct {
	ServiceUri string `protobuf:"bytes,1,opt,name=serviceUri" json:"serviceUri,omitempty"`
	Tags       string `protobuf:"bytes,2,opt,name=tags" json:"tags,omitempty"`
}

func (m *ServiceInstanceResponse) Reset()                    { *m = ServiceInstanceResponse{} }
func (m *ServiceInstanceResponse) String() string            { return proto.CompactTextString(m) }
func (*ServiceInstanceResponse) ProtoMessage()               {}
func (*ServiceInstanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceInstanceResponse) GetServiceUri() string {
	if m != nil {
		return m.ServiceUri
	}
	return ""
}

func (m *ServiceInstanceResponse) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

type AddRoutingKeyRequest struct {
	ServiceUri string `protobuf:"bytes,1,opt,name=serviceUri" json:"serviceUri,omitempty"`
	Tags       string `protobuf:"bytes,2,opt,name=tags" json:"tags,omitempty"`
	RoutingKey string `protobuf:"bytes,3,opt,name=routingKey" json:"routingKey,omitempty"`
}

func (m *AddRoutingKeyRequest) Reset()                    { *m = AddRoutingKeyRequest{} }
func (m *AddRoutingKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*AddRoutingKeyRequest) ProtoMessage()               {}
func (*AddRoutingKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddRoutingKeyRequest) GetServiceUri() string {
	if m != nil {
		return m.ServiceUri
	}
	return ""
}

func (m *AddRoutingKeyRequest) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *AddRoutingKeyRequest) GetRoutingKey() string {
	if m != nil {
		return m.RoutingKey
	}
	return ""
}

type DeleteRoutingKeyRequest struct {
	ServiceUri string `protobuf:"bytes,1,opt,name=serviceUri" json:"serviceUri,omitempty"`
	RoutingKey string `protobuf:"bytes,3,opt,name=routingKey" json:"routingKey,omitempty"`
}

func (m *DeleteRoutingKeyRequest) Reset()                    { *m = DeleteRoutingKeyRequest{} }
func (m *DeleteRoutingKeyRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRoutingKeyRequest) ProtoMessage()               {}
func (*DeleteRoutingKeyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteRoutingKeyRequest) GetServiceUri() string {
	if m != nil {
		return m.ServiceUri
	}
	return ""
}

func (m *DeleteRoutingKeyRequest) GetRoutingKey() string {
	if m != nil {
		return m.RoutingKey
	}
	return ""
}

func init() {
	proto.RegisterType((*RoutingKeyRequest)(nil), "api.RoutingKeyRequest")
	proto.RegisterType((*ServiceInstanceResponse)(nil), "api.ServiceInstanceResponse")
	proto.RegisterType((*AddRoutingKeyRequest)(nil), "api.AddRoutingKeyRequest")
	proto.RegisterType((*DeleteRoutingKeyRequest)(nil), "api.DeleteRoutingKeyRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Els service

type ElsClient interface {
	// Get a service by routingKey
	GetServiceInstanceByKey(ctx context.Context, in *RoutingKeyRequest, opts ...grpc.CallOption) (*ServiceInstanceResponse, error)
	// Add a routingKey to a service
	AddRoutingKey(ctx context.Context, in *AddRoutingKeyRequest, opts ...grpc.CallOption) (*ServiceInstanceResponse, error)
	// Add a routingKey to a service
	RemoveRoutingKey(ctx context.Context, in *DeleteRoutingKeyRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type elsClient struct {
	cc *grpc.ClientConn
}

func NewElsClient(cc *grpc.ClientConn) ElsClient {
	return &elsClient{cc}
}

func (c *elsClient) GetServiceInstanceByKey(ctx context.Context, in *RoutingKeyRequest, opts ...grpc.CallOption) (*ServiceInstanceResponse, error) {
	out := new(ServiceInstanceResponse)
	err := grpc.Invoke(ctx, "/api.Els/GetServiceInstanceByKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elsClient) AddRoutingKey(ctx context.Context, in *AddRoutingKeyRequest, opts ...grpc.CallOption) (*ServiceInstanceResponse, error) {
	out := new(ServiceInstanceResponse)
	err := grpc.Invoke(ctx, "/api.Els/AddRoutingKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elsClient) RemoveRoutingKey(ctx context.Context, in *DeleteRoutingKeyRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.Els/RemoveRoutingKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Els service

type ElsServer interface {
	// Get a service by routingKey
	GetServiceInstanceByKey(context.Context, *RoutingKeyRequest) (*ServiceInstanceResponse, error)
	// Add a routingKey to a service
	AddRoutingKey(context.Context, *AddRoutingKeyRequest) (*ServiceInstanceResponse, error)
	// Add a routingKey to a service
	RemoveRoutingKey(context.Context, *DeleteRoutingKeyRequest) (*google_protobuf.Empty, error)
}

func RegisterElsServer(s *grpc.Server, srv ElsServer) {
	s.RegisterService(&_Els_serviceDesc, srv)
}

func _Els_GetServiceInstanceByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutingKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElsServer).GetServiceInstanceByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Els/GetServiceInstanceByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElsServer).GetServiceInstanceByKey(ctx, req.(*RoutingKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Els_AddRoutingKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoutingKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElsServer).AddRoutingKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Els/AddRoutingKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElsServer).AddRoutingKey(ctx, req.(*AddRoutingKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Els_RemoveRoutingKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoutingKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElsServer).RemoveRoutingKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Els/RemoveRoutingKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElsServer).RemoveRoutingKey(ctx, req.(*DeleteRoutingKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Els_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Els",
	HandlerType: (*ElsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInstanceByKey",
			Handler:    _Els_GetServiceInstanceByKey_Handler,
		},
		{
			MethodName: "AddRoutingKey",
			Handler:    _Els_AddRoutingKey_Handler,
		},
		{
			MethodName: "RemoveRoutingKey",
			Handler:    _Els_RemoveRoutingKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "els.proto",
}

func init() { proto.RegisterFile("els.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0xd7, 0x56, 0x84, 0x5d, 0x50, 0xf4, 0x22, 0x6b, 0xad, 0x22, 0x12, 0x5f, 0x7c, 0xca,
	0x40, 0x3f, 0x81, 0xe2, 0x10, 0x1d, 0x3e, 0x18, 0xf1, 0xc1, 0xc7, 0x6e, 0xbd, 0x96, 0x48, 0xd7,
	0xc4, 0x26, 0x1d, 0xf4, 0x5b, 0xfb, 0x11, 0x64, 0x89, 0x7f, 0xa6, 0x73, 0xa8, 0x7b, 0x0b, 0xe7,
	0xe6, 0x9c, 0x03, 0x3f, 0x0e, 0x74, 0xa9, 0x34, 0x5c, 0xd7, 0xca, 0x2a, 0x8c, 0x32, 0x2d, 0xd3,
	0xbd, 0x42, 0xa9, 0xa2, 0xa4, 0xbe, 0x93, 0x46, 0xcd, 0x63, 0x9f, 0x26, 0xda, 0xb6, 0xfe, 0x07,
	0x3b, 0x82, 0x6d, 0xa1, 0x1a, 0x2b, 0xab, 0x62, 0x48, 0xad, 0xa0, 0xe7, 0x86, 0x8c, 0xc5, 0x4d,
	0x08, 0x65, 0x9e, 0x04, 0x87, 0xc1, 0x71, 0x57, 0x84, 0x32, 0x67, 0x37, 0x10, 0xdf, 0x51, 0x3d,
	0x95, 0x63, 0xba, 0xaa, 0x8c, 0xcd, 0xaa, 0x31, 0x09, 0x32, 0x5a, 0x55, 0x86, 0xf0, 0x00, 0xc0,
	0xf8, 0xd3, 0x7d, 0x2d, 0xdf, 0x2c, 0x73, 0x0a, 0x22, 0xac, 0xd9, 0xac, 0x30, 0x49, 0xe8, 0x2e,
	0xee, 0xcd, 0x9e, 0x60, 0xe7, 0x2c, 0xcf, 0x17, 0x6b, 0x57, 0xc8, 0x9a, 0x79, 0xea, 0x8f, 0xa0,
	0x24, 0xf2, 0x9e, 0x4f, 0x85, 0x3d, 0x40, 0x7c, 0x41, 0x25, 0x59, 0xfa, 0x7f, 0xdd, 0x2f, 0xd1,
	0x27, 0x2f, 0x01, 0x44, 0x83, 0xd2, 0xe0, 0x2d, 0xc4, 0x97, 0x64, 0xbf, 0x01, 0x3a, 0x6f, 0x87,
	0xd4, 0x62, 0x8f, 0x67, 0x5a, 0xf2, 0x85, 0xea, 0x74, 0xdf, 0xe9, 0x4b, 0x98, 0xb2, 0x0e, 0x5e,
	0xc3, 0xc6, 0x17, 0x42, 0xb8, 0xeb, 0x0c, 0x3f, 0x51, 0xfb, 0x43, 0xd6, 0x96, 0xa0, 0x89, 0x9a,
	0xce, 0x11, 0x40, 0xef, 0x59, 0x02, 0x26, 0xed, 0x71, 0xbf, 0x18, 0xfe, 0xbe, 0x18, 0x3e, 0x98,
	0x2d, 0x86, 0x75, 0x46, 0xeb, 0x4e, 0x39, 0x7d, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x00, 0x4c,
	0xc1, 0x63, 0x02, 0x00, 0x00,
}
