// Code generated by protoc-gen-go.
// source: els.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	els.proto

It has these top-level messages:
	Entity
	ServiceInstance
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Entity struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ServiceInstance struct {
	ServiceUri string `protobuf:"bytes,1,opt,name=serviceUri" json:"serviceUri,omitempty"`
	Tags       string `protobuf:"bytes,2,opt,name=tags" json:"tags,omitempty"`
}

func (m *ServiceInstance) Reset()                    { *m = ServiceInstance{} }
func (m *ServiceInstance) String() string            { return proto.CompactTextString(m) }
func (*ServiceInstance) ProtoMessage()               {}
func (*ServiceInstance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceInstance) GetServiceUri() string {
	if m != nil {
		return m.ServiceUri
	}
	return ""
}

func (m *ServiceInstance) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func init() {
	proto.RegisterType((*Entity)(nil), "api.Entity")
	proto.RegisterType((*ServiceInstance)(nil), "api.ServiceInstance")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Els service

type ElsClient interface {
	// Get a service
	GetServiceInstance(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*ServiceInstance, error)
}

type elsClient struct {
	cc *grpc.ClientConn
}

func NewElsClient(cc *grpc.ClientConn) ElsClient {
	return &elsClient{cc}
}

func (c *elsClient) GetServiceInstance(ctx context.Context, in *Entity, opts ...grpc.CallOption) (*ServiceInstance, error) {
	out := new(ServiceInstance)
	err := grpc.Invoke(ctx, "/api.Els/GetServiceInstance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Els service

type ElsServer interface {
	// Get a service
	GetServiceInstance(context.Context, *Entity) (*ServiceInstance, error)
}

func RegisterElsServer(s *grpc.Server, srv ElsServer) {
	s.RegisterService(&_Els_serviceDesc, srv)
}

func _Els_GetServiceInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ElsServer).GetServiceInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Els/GetServiceInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ElsServer).GetServiceInstance(ctx, req.(*Entity))
	}
	return interceptor(ctx, in, info, handler)
}

var _Els_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Els",
	HandlerType: (*ElsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInstance",
			Handler:    _Els_GetServiceInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "els.proto",
}

func init() { proto.RegisterFile("els.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xcd, 0x29, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x92, 0xe0, 0x62, 0x73, 0xcd,
	0x2b, 0xc9, 0x2c, 0xa9, 0x14, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x62, 0xca, 0x4c, 0x51, 0x72, 0xe5, 0xe2, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xf5,
	0xcc, 0x2b, 0x2e, 0x49, 0xcc, 0x4b, 0x4e, 0x15, 0x92, 0xe3, 0xe2, 0x2a, 0x86, 0x08, 0x85, 0x16,
	0x65, 0x42, 0x95, 0x22, 0x89, 0x08, 0x09, 0x71, 0xb1, 0x94, 0x24, 0xa6, 0x17, 0x4b, 0x30, 0x81,
	0x65, 0xc0, 0x6c, 0x23, 0x07, 0x2e, 0x66, 0xd7, 0x9c, 0x62, 0x21, 0x4b, 0x2e, 0x21, 0xf7, 0xd4,
	0x12, 0x74, 0x03, 0xb9, 0xf5, 0x12, 0x0b, 0x32, 0xf5, 0x20, 0x0e, 0x90, 0x12, 0x01, 0x73, 0xd0,
	0x94, 0x28, 0x31, 0x24, 0xb1, 0x81, 0x9d, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xf7,
	0xc2, 0x53, 0xbb, 0x00, 0x00, 0x00,
}
